[package]
name = "storethehash"
version = "0.1.0"
authors = ["Volker Mische <volker.mische@gmail.com>"]
edition = "2018"

[dependencies]
thiserror = "1.0.22"

[dev-dependencies]
tempfile = "3.1.0"
cid = "0.6.0"
