[package]
name = "storethehash-cid"
version = "0.1.0"
authors = ["Volker Mische <volker.mische@gmail.com>"]
edition = "2018"

[dependencies]
storethehash = { path = "../../" }
cid = { version = "0.6.0", default-features = false, features = ["std"] }
wasabi_leb128 = "0.4.0"
log = "0.4.11"
